apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
    - protocol: TCP
      port: 80       # Exposed port on the service
      targetPort: 8001  # Port your application is listening on inside the container
      nodePort: 30080   # Node port for accessing the service externally
